CREATE TABLE USUARIO (

ID SERIAL,
PRIMARY KEY(ID),
NOME VARCHAR(25),
ENDERECO VARCHAR(25),
DATANASCIMENTO VARCHAR(25),
FOTO VARCHAR(25),
CIDADE VARCHAR(25),
ESTADO VARCHAR(4),
BAIRRO VARCHAR(25),
CEP INTEGER,
EMAIL VARCHAR (25),
USERNAME VARCHAR(25),
SENHA VARCHAR(25),
ATIVO INTEGER ,
TIPO INTEGER
);
/**/

CREATE TABLE EMPRESA(
ID SERIAL,
PRIMARY KEY(ID),
TITULO VARCHAR(25),
FOTO VARCHAR(25),
DESCRICAO VARCHAR(200),
COMOTRABALHAMOS VARCHAR(200),
SONHO VARCHAR(200),
MISSAO VARCHAR(200),
VALORES VARCHAR(200)
);

CREATE TABLE CIDADE(

ID SERIAL,
PRIMARY KEY(ID),
CIDADE VARCHAR(50),
LOCAL VARCHAR(50),
HORARIO VARCHAR(20),
LOCAL_GRUPO INTEGER,
FOREIGN KEY (LOCAL_GRUPO) REFERENCES LOCAL_GRUPO
);

CREATE TABLE LOCAL(
ID SERIAL,
PRIMARY KEY(ID),
DATA DATE
);
CREATE TABLE VIAGENS (

ID SERIAL,
PRIMARY KEY(ID),
CATEGORIA INTEGER,
TITULO VARCHAR(50),
DESCRICAO VARCHAR(200),
OQUEINCLUI VARCHAR(200),
OQUELEVAR VARCHAR(200),
ROTEIRO VARCHAR(200),
ITINERARIO VARCHAR(200),
VAGAS INTEGER,
DICAS VARCHAR(200),
VALOR VARCHAR(20),
PROMOCAO VARCHAR(20),
LOCAL_GRUPO INTEGER,
EMPRESA INTEGER,
FOREIGN KEY (EMPRESA) REFERENCES EMPRESA,
FOREIGN KEY (LOCAL_GRUPO) REFERENCES LOCAL_GRUPO,
IMAGEM_VIAGENS_GRUPO INTEGER,
FOREIGN KEY (IMAGEM_VIAGENS_GRUPO) REFERENCES IMAGEM_VIAGENS_GRUPO
);

/*TABELA PARA AS IMAGENS DAS VIAGENS*/
CREATE TABLE IMAGEM_VIAGENS (
ID SERIAL,
PRIMARY KEY(ID)
IMAGEM_VIAGENS_GRUPO INTEGER,
FOTO VARCHAR(25),
FOREIGN KEY (IMAGEM_VIAGENS_GRUPO) REFERENCES IMAGEM_VIAGENS_GRUPO
);


CREATE TABLE IMAGEM_VIAGENS_GRUPO(
TITULO VARCHAR(50),
ID SERIAL,
PRIMARY KEY(ID)

);

CREATE TABLE VIAGEM_CLIENTES (

TITULO VARCHAR(25),
VALOR VARCHAR(25),
STATUS INTEGER,
CLIENTEID INTEGER,
FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES,
VIAGEMID INTEGER,
FOREIGN KEY (VIAGEMID) REFERENCES VIAGENS
);

/*FUNCAO CEP AUTOMATICO*/
/*FORMULARIO PASSO 1 PASSO 2*/





